alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gco='git checkout'
alias gac='git commit -a'
alias gp='git push'
alias gpo='git push origin'
alias gl='git pull'
alias glo='git pull origin'
alias gm='git merge --no-ff'
alias gr='git reset'
alias grh='git reset --hard'
alias gre='git remote'
alias grm="git rm"
alias gcl="git clone"
alias gd="git diff"
alias gds="git diff --staged"
alias gb='git branch'
alias gbd='git branch -d'
alias gf='git fetch'
alias gfo='git fetch origin'
